Parameters:
  EnvID:
    Type: String

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: PICK
      ImageId: ami-080e1f13689e07408
      VpcId:
        Fn::ImportValue: 
          !Sub "${EnvID}-VPCId"

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref Ec2Instance

Outputs:
  InstanceId:
    Description: "InstanceId of the newly created EC2 instance"
    Value: 
      Ref: "Ec2Instance"
  PublicIp:
    Description: "Public IP address of the newly created EC2 instance"
    Value: 
      Fn::GetAtt: 
        - "Ec2Instance"
        - "PublicIp"